[project]
name = "what2watchnextbot"
version = "0.1.0"
description = ""
authors = [
    { name = "Anton Trotsenko", email = "trotsenko.ant07@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "sqlalchemy[postgresql-psycopgbinary,asyncio] (>=2.0.0,<2.1.0)",
    "alembic (>=1.14.0,<2.0.0)",
    "pandas (>=2.2.0,<3.0.0)",
    "aiogram[redis] (>=3.17.0,<3.19.0)",
    "loguru (>=0.7.0,<0.8.0)",
    "click (>=8.1.0,<9.0.0)",
    "python-dotenv",
    "pydantic-settings (>=2.7.1,<3.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
]

[project.scripts]
what2watchnextbot = "what2watchnextbot.cli:cli"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.2"
pre-commit = "^4.0.1"
watchfiles = "^1.0.3"

[tool.poetry.group.research.dependencies]
jupyter = "*"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
