[project]
name = "tg-bot-template"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiogram-loguru>=0.1.2",
    "aiogram[fast,i18n,redis]>=3.19.0",
    "alembic>=1.15.2",
    "loguru>=0.7.3",
    "pydantic-settings>=2.8.1",
    "sqlalchemy[postgresql-psycopgbinary]>=2.0.40",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "ruff>=0.11.5",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
required_plugins = [
    "pytest-asyncio",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # flake8-bugbear
    "B",
    # isort
    "I",
]