[tool.poetry]
name = "what2watchnextbot"
version = "0.1.0"
description = ""
authors = ["antos07 <trotsenko.ant07@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
sqlalchemy = { extras = ["postgresql-psycopgbinary", "asyncio"], version = "^2.0.36" }
alembic = "^1.14.0"
jupyter = "^1.1.1"
pandas = "^2.2.3"
notebook = "^7.3.2"
aiogram = {version = "~3.17", extras = ["redis"]}
loguru = "^0.7.3"
click = "^8.1.8"
python-dotenv = "^1.0.1"
pydantic-settings = "^2.7.1"
tqdm = "^4.67.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.8.4"
pre-commit = "^4.0.1"
watchfiles = "^1.0.3"

[tool.poetry.scripts]
what2watchnextbot = "what2watchnextbot.cli:cli"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
