"""Add User.last_activity_at field

Revision ID: 38cdcc0adc6b
Revises: 81f22f1bc935
Create Date: 2025-01-20 17:50:32.594294

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38cdcc0adc6b"
down_revision: Union[str, None] = "81f22f1bc935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("user", sa.Column("last_activity_at", sa.DateTime(), nullable=True))

    upgrade_data()

    op.alter_column("user", "last_activity_at", nullable=False)


def upgrade_data() -> None:
    metadata = sa.MetaData()
    # Partial user table definition
    user_table = sa.Table(
        "user",
        metadata,
        sa.Column("last_activity_at", sa.DateTime()),
        sa.Column("last_settings_update_at", sa.DateTime()),
    )
    update_stmt = sa.update(user_table).values(
        last_activity_at=user_table.c.last_settings_update_at
    )
    op.execute(update_stmt)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_activity_at")
    # ### end Alembic commands ###
