"""Update foreign keys to provide ON DELETE action

Revision ID: 3ac1e5da88d5
Revises: efaec3a30a78
Create Date: 2025-01-05 19:11:07.583636

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ac1e5da88d5"
down_revision: Union[str, None] = "efaec3a30a78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_genre_title_table_genre_id_genre", "genre_title_table", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_genre_title_table_title_id_title", "genre_title_table", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_genre_title_table_genre_id_genre"),
        "genre_title_table",
        "genre",
        ["genre_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_genre_title_table_title_id_title"),
        "genre_title_table",
        "title",
        ["title_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_selected_genres_user_id_user", "selected_genres", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_selected_genres_genre_id_genre", "selected_genres", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_selected_genres_user_id_user"),
        "selected_genres",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_selected_genres_genre_id_genre"),
        "selected_genres",
        "genre",
        ["genre_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_selected_genres_genre_id_genre"), "selected_genres", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_selected_genres_user_id_user"), "selected_genres", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_selected_genres_genre_id_genre",
        "selected_genres",
        "genre",
        ["genre_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_selected_genres_user_id_user",
        "selected_genres",
        "user",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_genre_title_table_title_id_title"),
        "genre_title_table",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_genre_title_table_genre_id_genre"),
        "genre_title_table",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_genre_title_table_title_id_title",
        "genre_title_table",
        "title",
        ["title_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_genre_title_table_genre_id_genre",
        "genre_title_table",
        "genre",
        ["genre_id"],
        ["id"],
    )
    # ### end Alembic commands ###
