"""Update genre_title and selected_genres tables with additional indexes

Revision ID: 5525a2ab6a30
Revises: 3ac1e5da88d5
Create Date: 2025-01-05 19:58:33.036051

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5525a2ab6a30"
down_revision: Union[str, None] = "3ac1e5da88d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_genre_title_table_genre_id"),
        "genre_title_table",
        ["genre_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_genre_title_table_title_id"),
        "genre_title_table",
        ["title_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_selected_genres_genre_id"),
        "selected_genres",
        ["genre_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_selected_genres_user_id"), "selected_genres", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_selected_genres_user_id"), table_name="selected_genres")
    op.drop_index(op.f("ix_selected_genres_genre_id"), table_name="selected_genres")
    op.drop_index(op.f("ix_genre_title_table_title_id"), table_name="genre_title_table")
    op.drop_index(op.f("ix_genre_title_table_genre_id"), table_name="genre_title_table")
    # ### end Alembic commands ###
