"""Add User.watched_titles and User.ignored_titles relationships

Revision ID: 72e8938336f5
Revises: 5525a2ab6a30
Create Date: 2025-01-05 20:17:38.648687

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72e8938336f5"
down_revision: Union[str, None] = "5525a2ab6a30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ignored_titles",
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
            name=op.f("fk_ignored_titles_title_id_title"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_ignored_titles_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("title_id", "user_id", name=op.f("pk_ignored_titles")),
    )
    op.create_index(
        op.f("ix_ignored_titles_title_id"), "ignored_titles", ["title_id"], unique=False
    )
    op.create_index(
        op.f("ix_ignored_titles_user_id"), "ignored_titles", ["user_id"], unique=False
    )
    op.create_table(
        "watched_titles",
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
            name=op.f("fk_watched_titles_title_id_title"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_watched_titles_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("title_id", "user_id", name=op.f("pk_watched_titles")),
    )
    op.create_index(
        op.f("ix_watched_titles_title_id"), "watched_titles", ["title_id"], unique=False
    )
    op.create_index(
        op.f("ix_watched_titles_user_id"), "watched_titles", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watched_titles_user_id"), table_name="watched_titles")
    op.drop_index(op.f("ix_watched_titles_title_id"), table_name="watched_titles")
    op.drop_table("watched_titles")
    op.drop_index(op.f("ix_ignored_titles_user_id"), table_name="ignored_titles")
    op.drop_index(op.f("ix_ignored_titles_title_id"), table_name="ignored_titles")
    op.drop_table("ignored_titles")
    # ### end Alembic commands ###
