"""Create Title and Genre models

Revision ID: 7ff4da84bbd4
Revises:
Create Date: 2025-01-02 15:03:59.811504

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ff4da84bbd4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_genre")),
    )
    op.create_index(op.f("ix_genre_name"), "genre", ["name"], unique=True)
    op.create_table(
        "title",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("MOVIE", "SERIES", "MINI_SERIES", name="titletypes"),
            nullable=False,
        ),
        sa.Column("start_year", sa.Integer(), nullable=False),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("votes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_title")),
    )
    op.create_index(op.f("ix_title_rating"), "title", ["rating"], unique=False)
    op.create_index(op.f("ix_title_start_year"), "title", ["start_year"], unique=False)
    op.create_index(op.f("ix_title_votes"), "title", ["votes"], unique=False)
    op.create_table(
        "genre_title_table",
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"], ["genre.id"], name=op.f("fk_genre_title_table_genre_id_genre")
        ),
        sa.ForeignKeyConstraint(
            ["title_id"], ["title.id"], name=op.f("fk_genre_title_table_title_id_title")
        ),
        sa.PrimaryKeyConstraint(
            "genre_id", "title_id", name=op.f("pk_genre_title_table")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("genre_title_table")
    op.drop_index(op.f("ix_title_votes"), table_name="title")
    op.drop_index(op.f("ix_title_start_year"), table_name="title")
    op.drop_index(op.f("ix_title_rating"), table_name="title")
    op.drop_table("title")
    op.drop_index(op.f("ix_genre_name"), table_name="genre")
    op.drop_table("genre")
    # ### end Alembic commands ###
