"""Add selected_title_types table

Revision ID: 81f22f1bc935
Revises: c2731944931a
Create Date: 2025-01-17 18:29:44.875711

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81f22f1bc935"
down_revision: Union[str, None] = "c2731944931a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    title_types_enum = sa.Enum("MOVIE", "SERIES", "MINI_SERIES", name="titletypes")
    if op.get_context().dialect.name == "postgresql":
        title_types_enum = postgresql.ENUM(name="titletypes", create_type=False)

    op.create_table(
        "selected_title_types",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            title_types_enum,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_selected_title_types_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "type", name=op.f("pk_selected_title_types")
        ),
    )
    op.create_index(
        op.f("ix_selected_title_types_user_id"),
        "selected_title_types",
        ["user_id"],
        unique=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_selected_title_types_user_id"), table_name="selected_title_types"
    )
    op.drop_table("selected_title_types")
    # ### end Alembic commands ###
