"""Add User.skipped_titles and TitleSkip model

Revision ID: b88e2ac374af
Revises: 83376a8a2aa3
Create Date: 2025-08-01 20:42:02.900947

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b88e2ac374af"
down_revision: Union[str, None] = "83376a8a2aa3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "titleskip",
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("is_watched", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["title_id"], ["title.id"], name=op.f("fk_titleskip_title_id_title")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_titleskip_user_id_user")
        ),
        sa.PrimaryKeyConstraint("title_id", "user_id", name=op.f("pk_titleskip")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("titleskip")
    # ### end Alembic commands ###
