"""Add User.selected_genres relationship

Revision ID: ba72a10f52d2
Revises: 02c4ac8f5d44
Create Date: 2025-01-02 18:32:49.807334

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba72a10f52d2"
down_revision: Union[str, None] = "02c4ac8f5d44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "selected_genres",
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"], ["genre.id"], name=op.f("fk_selected_genres_genre_id_genre")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_selected_genres_user_id_user")
        ),
        sa.PrimaryKeyConstraint("genre_id", "user_id", name=op.f("pk_selected_genres")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("selected_genres")
    # ### end Alembic commands ###
