"""Add User.minimum_votes field

Revision ID: c2731944931a
Revises: d2b81796f759
Create Date: 2025-01-17 16:08:25.177274

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2731944931a"
down_revision: Union[str, None] = "d2b81796f759"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "user",
        sa.Column(
            "minimum_votes",
            sa.Integer(),
            nullable=False,
            server_default=sa.literal(10000),
        ),
    )
    op.alter_column("user", "minimum_votes", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "minimum_votes")
    # ### end Alembic commands ###
