"""Add User.minimum_rating field

Revision ID: d2b81796f759
Revises: 9ed0bf6dd254
Create Date: 2025-01-17 16:04:42.592147

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2b81796f759"
down_revision: Union[str, None] = "9ed0bf6dd254"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "user",
        sa.Column(
            "minimum_rating", sa.Integer(), nullable=False, server_default=sa.literal(6)
        ),
    )
    op.alter_column("user", "minimum_rating", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "minimum_rating")
    # ### end Alembic commands ###
