"""Add User.last_settings_update_at field

Revision ID: efaec3a30a78
Revises: ba72a10f52d2
Create Date: 2025-01-05 11:48:04.858253

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efaec3a30a78"
down_revision: Union[str, None] = "ba72a10f52d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("last_settings_update_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_settings_update_at")
    # ### end Alembic commands ###
