name: CD
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      SSH_KEY_PATH: ${{ github.workspace }}/../private.key

    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Deploy a new version
        run: |
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST << EOF
            cd ~/What2WatchNextBot
            git pull
            systemctl --user restart what2watchnextbot.service
            uv run alembic upgrade head
          EOF
        env:
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_HOST: ${{secrets.SSH_HOST}}
