name: CI

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

permissions:
  contents: read

jobs:
  code-style:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --dev

      - name: Check formatting
        run: ruff format --check

      - name: Run linter
        run: ruff check

  tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --dev

      - name: Run tests
        run: pytest
        env:
          DB_DSN: postgresql+psycopg://postgres:postgres@localhost:5432/postgres
